version: '3.0'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/usr/src/app
    ports:
      - "49160:3000"
    command: npm run build:docker:prod

  dev:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "49160:3000"
    command: npm run build:docker:dev
